# Generated by Django 5.2.15 on 2026-07-27 04:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bahia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('en_espera', 'En Espera')], default='libre', max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('pos_x', models.PositiveIntegerField(default=0)),
                ('pos_y', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('unidad', models.CharField(default='unidad', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('oficinista', 'Oficinista'), ('cliente', 'Cliente'), ('mecanico', 'Mecánico')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('general', 'Mecánica General'), ('electrico', 'Sistema Eléctrico'), ('transmision', 'Transmisión'), ('suspension', 'Suspensión y Frenos'), ('carroceria', 'Carrocería y Pintura')], default='general', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_mecanico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('descripcion', models.TextField(help_text='Problema reportado por el cliente')),
                ('observaciones', models.TextField(blank=True, help_text='Notas internas del mecánico', null=True)),
                ('kilometraje_ingreso', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_estimada_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_entrega', models.DateTimeField(blank=True, null=True)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bahia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='facturacion.bahia')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='facturacion.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p01_frenos_delanteros', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p02_frenos_traseros', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p03_aceite_motor', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p04_liquido_frenos', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p05_liquido_refrigerante', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p06_bateria', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p07_alternador', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p08_filtro_aire', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p09_bujias', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p10_correa_distribucion', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p11_suspension_delantera', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p12_suspension_trasera', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p13_neumaticos', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p14_alineacion', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p15_escape', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p16_transmision', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p17_direccion', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p18_luces', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p19_limpiabrisas', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('p20_carroceria_visual', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('falla', 'Falla'), ('na', 'No Aplica')], default='na', max_length=6)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('realizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion', to='facturacion.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='facturacion.ordentrabajo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_repuestos', to='facturacion.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='facturacion.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo', models.CharField(choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('pickup', 'Pick-up'), ('hatchback', 'Hatchback'), ('furgon', 'Furgón'), ('otro', 'Otro')], default='sedan', max_length=30)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('numero_motor', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=60, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='facturacion.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='facturacion.vehiculo'),
        ),
    ]
