# Generated by Django 5.2.15 on 2026-07-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_chasis',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_motor',
        ),
    ]
