# Generated by Django 5.2.15 on 2026-07-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_vehiculo_remove_motor_chasis_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='kilometraje',
        ),
    ]
